docs/user/_sources/_static/params/anat_config.csv
docs/user/_sources/_static/params/ftm_config.csv
docs/user/_sources/anat.txt
docs/user/_sources/func.txt

Reverts FCP-INDI/fcp-indi.github.com#142
Accidentally merged into source before releasing, oops.

Revert "Added float resolution options"

---

docs/user/_sources/anat.txt

add niworkflows-ants for skull-stripping

add niworkflows-ants for skulll-stripping

---

docs/developer/_sources/developer/installation.rst
docs/developer/_sources/developer/installation.rst.txt
docs/developer/_sources/developer/testing.rst
docs/developer/_sources/developer/testing.rst.txt
docs/developer/_sources/developer/workflow_documentation.rst
docs/developer/_sources/developer/workflow_documentation.rst.txt

http://fcp-indi.github.io/docs/developer/developer/index.html

📚✏️ Update "C-PAC 1.5.0 Beta documentation » For Developers" with relevant links

---

docs/user/_sources/_static/params/func_init_config.csv

Ref
```
/build/docs/user/_sources/func.txt:27: WARNING: Error with CSV data in "csv-table" directive:
',' expected after '"'
```

🚑 Reformat CSV

---

.circleci/config.yml
docs/user/_sources/run/help.txt

🚑 Correct path to C-PAC for Circle build

---

docs/user/_sources/subject_list_config.txt

Ref https://github.com/FCP-INDI/C-PAC/issues/1252

📚 Bind data directories for `data_config build`

---

.circleci/config.yml
CONTRIBUTING.md

This PR updates the CI configuration to build the versioned docs from git tags in the format `v<version>-source`, deprecating the need for a `build_version.txt` file. This PR also updates [CONTRIBUTING.md](https://github.com/FCP-INDI/fcp-indi.github.com/blob/23f146dc9572b9f66fd2945bb23da9b876eb1425/CONTRIBUTING.md) to reflect this change.
index.md`).
visible errors.
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```

:rocket: Build versions for tags

---

docs/_sources/user/anat.rst

Flowcharts not appearing on [Anatomical Preprocessing](https://fcp-indi.github.io/docs/latest/user/anat) page
Fixes off-by-one path for SVGs
index.md`).
visible errors.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```

✏️ Fix path to anat flowcharts

---

.circleci/config.yml
CONTRIBUTING.md
docs/_sources/_static/custom.css
docs/_sources/conf.py
docs/_sources/developer/atlas_support.rst
docs/_sources/glossary/atlas.rst
docs/_sources/glossary/template.rst
docs/_sources/references/__init__.py
docs/_sources/references/cifti.bib
docs/_sources/references/glossary.bib
docs/_sources/references/style.py
docs/_sources/user/pipeline_config.rst
docs/_sources/user/quick.rst

Fixes #231 by @shnizzedy & @lgibson212
1. Adds to the bottom of [docs/nightly/user/pipeline_config#definitions](https://fcp-indi.github.io/docs/nightly/user/pipeline_config#definitions):
> * Atlas
> > > An _atlas_ provides a guide to the location of anatomical features in a coordinate space.
> > > 
> > > —[1] p. 55
> > 
> > An atlas provides a defined coordinate space, a template for aligning images, and labels for regions of interest.
> >
> >  Currently C-PAC only supports atlases in NifTI format.
> >
> >  CIFTI is a popular atlas format not yet supported by C-PAC. As always, if anyone wants to share any tips or hacks with us, we are an open-source platform after all. Below are some resources that might help enable CIFTI atlas support in a future version of C-PAC.
> >
> >   **CIFTI …

📚 Document lack of support for CIFTI atlases

---

docs/_sources/developer/nodes.rst

Documents changes from https://github.com/FCP-INDI/C-PAC/pull/1531
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source
license …
```

📝 Document changes from "Fix Memory Bugs" (FCP-INDI/C-PAC#1531)

---

docs/_sources/user/nuisance.rst

Adds/restores an example custom regressor to the user docs.
Related: https://github.com/FCP-INDI/C-PAC_GUI/issues/120
<details>
```
Version 1.1
Suite D4700
of my knowledge, …
```

📝 Add custom regressor example

---

docs/_sources/references/style.py
docs/_sources/references/tse.bib
docs/_sources/user/tse.rst

Documents https://github.com/FCP-INDI/C-PAC/pull/1595 by @shnizzedy and @amygutierrez 
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate …
```

📝 Document timeseries connectivity matrices

---

docs/_sources/user/singularity.rst

Related to #264 by @shnizzedy 
Change `shub` URIs to `docker` URIs
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source
license …
```

👽️ Note Singularity Hub deprecation and remove calls to shub

---

docs/_sources/user/pipelines/preconfig.rst

Documents FCP-INDI/C-PAC#1644 by @shnizzedy 
Adds
> # rbc-options: ReproBrainChart Options Pipeline
> 
> Pipeline Configuration YAML:
> <https://github.com/FCP-INDI/C-PAC/blob/main/CPAC/resources/configs/pipeline_config_rbc-options.yml>
to [Pre-configured Pipelines](https://fcp-indi.github.io/docs/latest/user/pipelines/preconfig). I'm not sure if there's anything else to say about RBC there yet.
<details>
```
Version 1.1
Suite D4700
By making a …
```

📝 Add RBC-options to preconfig list

---

.circleci/config.yml
docs/_sources/_static/custom.css
docs/_sources/developer/nodes.rst
docs/_sources/user/anat.rst
docs/_sources/user/compute_config.rst

Documents https://github.com/FCP-INDI/C-PAC/pull/1701 by @shnizzedy
---
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate open source …
```

📝 Document "✨ Add `--runtime_usage` flag (FCP-INDI/C-PAC#1701)"

---

docs/_sources/user/index.rst

Updates [The C-PAC Team](https://fcp-indi.github.io/docs/latest/user/index.html#the-c-pac-team)
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an …
```

👥 Move Cameron and Lei to alumni & add Greg to dev team

---

docs/_sources/user/group_fsl_feat.rst
docs/_sources/user/help.rst
docs/_sources/user/output_dir.rst
docs/_sources/user/pipelines/design_a_pipeline.rst
docs/_sources/user/qc_interface.rst
docs/_sources/user/subject_list_config.rst
index.html

Replace all the links to https://groups.google.com/forum/#!forum/cpax_forum with links to https://neurostars.org/tag/cpac and update the wording around the links accordingly
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based …
```

📝 Replace Google Groups links with Neurostars links

---

docs/_sources/references/style.py
docs/_sources/references/tse.bib
docs/_sources/user/tse.rst

Documents https://github.com/FCP-INDI/C-PAC/issues/1642 (https://github.com/FCP-INDI/C-PAC/pull/1683/commits/c113089d7988e800c25a6ad1843e4a7ef8bf2b73 in https://github.com/FCP-INDI/C-PAC/pull/1683) by @shnizzedy
<details>
```
Version 1.1
Suite D4700
indicated in the …
```

📝 Document that ndmg connectome is now optional

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the PR template for this repository to be specific to this repository. I got tired of adjusting the text in the template every PR in this repo.
Before this PR, this repository is using [the organization-default PR template](https://github.com/FCP-INDI/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md). I merged that template into this repo and updated it [here](https://github.com/FCP-INDI/fcp-indi.github.io/commit/a16525ad54895942abe7737d9a9e50a8030797ea).
I copy-pasted the template from this PR and filled it for this PR description.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

🧑‍💻 Make PR template docs-repo-specific

---

docs/_sources/conf.py
docs/_sources/index.rst
docs/_sources/license.rst
index.html
scripts/forwardToLatest.js

Documents https://github.com/FCP-INDI/C-PAC/pull/1747 by @shnizzedy
* Updates docs footer from
> © Copyright 2020, C-PAC Team. Created using [Sphinx](https://www.sphinx-doc.org/) 4.4.0.
to
> © Copyright 2012‒2022, C-PAC Developers. C-PAC is licensed under LGPL-3.0-or-later. Created using [Sphinx](https://www.sphinx-doc.org/) 5.0.2.
* Updates landing page footer from
> © 2017-2018 [Child Mind Institute](https://childmind.org/)	|	Design: [HTML5 UP](http://html5up.net/)
to
> © 2017-2018 [Child Mind Institute](https://childmind.org/), © 2022 C-PAC Developers	|	Design: [HTML5 UP](http://html5up.net/)
* Adds a copy of LGPL-3.0-or-later to docs (at `fcp-indi.github.io/docs/«version»/license`)
* Updates forwarding script to forward `fcp-indi.github.io/docs/license` to …

📄 Add C-PAC license info to docs

---

docs/_sources/admonitions/DwellTime.rst
docs/_sources/user/func.rst

Documents https://github.com/FCP-INDI/C-PAC/pull/1781 by @shnizzedy 
* Updates the distortion correction documentation copy to specify `EffectiveEchoSpacing` instead of `DwellTime`
* Adds a warning about the prior state of usage
* We should probably add the warning to all the previous versions once C-PAC 1.8.5 is released.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```

📝 Document phasediff DwellTime correction

---

.circleci/config.yml
docs/_sources/developer/logging.rst

Documents FCP-INDI/C-PAC#1873 by @shnizzedy 
Adds "Logging `subprocess.check_outputs`" section with 
```rst
.. autofunction:: CPAC.utils.monitoring.custom_logging.log_subprocess
```
to [fcp-indi.github.io/docs/nightly/developer/logging](https://fcp-indi.github.io/docs/nightly/developer/logging)
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by …
```

📝 Document FCP-INDI/C-PAC#1873

---

.circleci/config.yml
docs/_sources/developer/nodes.rst
docs/_sources/user/compute_config.rst
docs/_sources/user/cpac.rst
docs/_sources/user/docker.rst
docs/_sources/user/group_fsl_feat.rst
docs/_sources/user/group_pybasc.rst
docs/_sources/user/pipelines/design_a_pipeline.rst
docs/_sources/user/pipelines/pipeline_config.rst
docs/_sources/user/pipelines/random_state.rst
docs/_sources/user/running.rst
docs/_sources/user/subject_list_config.rst
requirements.txt

Documents FCP-INDI/C-PAC#1958 by @shnizzedy (that PR needs to merge first for the <span title="single source of truth">SSOT</span>'d docs to generate with the updated code)
Updates examples in documentation to use canonical `-`s in place of backwards-compatible `_`s
* Upgrades a few dependencies
* <span title="single source of truth">SSOT</span>s https://github.com/FCP-INDI/fcp-indi.github.io/blob/92be1394279b460945443e8fd3c39b852e412f03/docs/_sources/user/group_fsl_feat.rst?plain=1#L60-L66 by adding the help call to what the CI runs at build 
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

📝 Document "👽 Update CLI to accept dashes and underscores where appropriate"

---

.circleci/config.yml
docs/_sources/developer/workflows/network_centrality.rst

Documents FCP-INDI/C-PAC#1998 by @shnizzedy
Adds autodocumentation of network centrality submodules to developer documentation
Changes the CI build image from a generic Python image to the nightly C-PAC image so dependency-version-specific code matches the latest dependency versions.
<details>
```
Version 1.1
Suite D4700 …
```

📝 Document "👽️ Handle versions of `3dECM`"

---

.circleci/config.yml
docs/_sources/user/cpac.rst

Documents https://github.com/FCP-INDI/cpac/pull/39, https://github.com/FCP-INDI/cpac/pull/40, https://github.com/FCP-INDI/cpac/pull/42 & https://github.com/FCP-INDI/cpac/pull/43 by @shnizzedy
Adds documentation for how to install and use the extra `cpac` commands `gradients` and `tsconcat`
The screenshots are built from the `HEAD` of [FCP-INDI/cpac@`extras/tsconcat`](https://github.com/FCP-INDI/cpac/tree/extras/tsconcat); we should wait to merge this PR until https://github.com/FCP-INDI/cpac/pull/40, https://github.com/FCP-INDI/cpac/pull/42 & https://github.com/FCP-INDI/cpac/pull/43 are all merged, and the `cpac` release is tagged and the CI pushes the release to PyPI.
<details>
```
Version 1.1
Copyright …
```

📝 Document `cpac` extras (`gradients` and `tsconcat`)

---

docs/_sources/user/subject_list_config.rst

Documents [https://github.com/FCP-INDI/C-PAC/issues/1902](https://github.com/FCP-INDI/C-PAC/issues/1902)
Added much needed documentation for FreeSurfer and fMRIPrep ingress. Tutorials to come!
<details>
```
Version 1.1
Suite D4700
(b) The …
```

📝 Document FS & fMRIPrep ingress

---

docs/_sources/user/subject_list_config.rst

The example config for the data config builder was let it crash before.
This PR includes the changes suggested to me in https://cmi-cnl.slack.com/archives/CBM95TMEW/p1707419014415849
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```

Fix data config builder config example

---

docs/_sources/user/alff.rst
docs/_sources/user/reho.rst

Documents [surface_derivatives](https://github.com/FCP-INDI/C-PAC/pull/1889)
This PR adds documentation for the newly added surface-based derivatives. 
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```

📝 Documentation for surface derivatives

---

docs/_sources/conf.py
requirements.txt

Resolves #313 by @shnizzedy 
Resolves "[the search feature isn't working in the cpac docs](https://cmi-cnl.slack.com/archives/C065W7YJ4V9/p1711466889754779)" by @e-kenneally 
When we updated the theme, some JS that was included in the old theme templates wasn't injected into the new theme. This PR restores those scripts.
Two of the same errors are still appearing in the console, one of which I think is from the script raising it double-loading, but search works with just the one error resolved.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```

🐛 Restore search functionality

---

docs/_sources/conf.py
docs/_sources/user/help.rst
docs/_sources/user/known-issues/FCP-INDI/C-PAC/2104.rst
docs/_sources/user/pipelines/preconfig.rst
requirements.txt

Documents FCP-INDI/C-PAC#2104 by @sgiavasis 
Resolves #318 by @shnizzedy 
Adds documentation and workarounds for FCP-INDI/C-PAC#2104 to [C-PAC nightly documentation » User » Troubleshooting and Help » Common Issues](https://fcp-indi.github.io/docs/nightly/user/help#common-issues)
I mostly just stole / moved around copy from the issue and [this Slack thread](https://cmi-cnl.slack.com/archives/C065W7YJ4V9/p1714594986068799)
<span id="technical-details" name="technical-details"></span>
Changes "Common Issues" section from an ordered list to a series of subsections to:
a) allow sub-subsections to be `include`d in the issue-specific documentation
b) include the issues in the sidebar TOC
(linked from abcd-options warning and included in "Common Issues")
<details>
<summary>Developer Certificate …

📝 Known issue: ABCD hanging

---

docs/_sources/user/known-issues/FCP-INDI/C-PAC/2110.rst

Documents https://github.com/FCP-INDI/C-PAC/pull/2170 by @shnizzedy 
Updates
> The ``bids-validator`` CLI was restored to the C-PAC container images in version 1.8.8.
to
> The ``bids-validator`` CLI was restored to the C-PAC container images in version 1.8.7.post1.
<details>
```
Version 1.1
Suite D4700
have the right to …
```

📌 Update version `bids-validator` was restored
